FROM node:8 as builder
RUN npm install -g create-react-app
RUN mkdir -p /app
RUN create-react-app /app
WORKDIR /app
RUN npm run build

FROM node:8
RUN npm install -g http-server
COPY --from=builder /app/build /app
WORKDIR /app
EXPOSE 8080
CMD ["http-server", "."]
