FROM python:3.7-rc-alpine

RUN apk update && apk add bash
RUN pip install aiohttp

RUN mkdir -p /app
WORKDIR /app
COPY environment-runner /usr/local/bin
COPY server.py server.py

EXPOSE 8080

ENTRYPOINT ["environment-runner"]
CMD ["python", "server.py"]
